project:
  type: website

website:
  title: "Amaeya Deshpande"
  navbar:
    right:
      - href: index.qmd
        text: Projects
      - href: about.qmd
        text: About
  page-footer: 
    right: "&copy; 2024, Amaeya Deshpande"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    
execute: 
  freeze: auto



